<script setup>
import {ref} from 'vue'
let dialog=ref();
function showprivacy()
{
  dialog.value=true;
}
</script>
<template>
  <p id="cp" class="text-subtitle-1">
    copyright <v-icon
          size="x-small"
          color="#ffffff"
          icon="mdi-copyright"
          class="ms-1 mb-1 mr-1"
          ></v-icon> Doria Arnaud
            <span id="privacybtn" class="ms-3" @click="showprivacy">
              Privacy policy
            </span>
  </p>
  <v-dialog
        v-model="dialog"
        transition="dialog-bottom-transition"
        fullscreen
      >
    <v-card>
      <v-toolbar color="#333351">
        <v-btn
          icon="mdi-close"
          @click="dialog = false"
        ></v-btn>
      </v-toolbar>
      <div class="privacycontainer ps-5 pt-2 pr-5">
        <h1 class="text-h4 mb-5">Privacy Policy</h1>
        <p>
          Last updated: May 08, 2024
        </p>
        <p>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p>
          The DNS of the website and the extension are registered with a legal DNS provider accredited by ICANN.
        </p>
        <p>
          We use Your Personal data like e-mail for a primary contact between You and Us.
        </p>
        <p>
          For the purposes of this Privacy Policy:
        </p>
        <ul class="ms-5">
          <li>
            <p><strong>Device</strong> means any device that can access this website such as a computer, a cellphone or a digital tablet.</p>
          </li>
          <li>
            <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
          </li>
          <li>
            <p><strong>Service</strong> refers to the Website.</p>
          </li>
          <li>
            <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
          </li>
          <li>
            <p><strong>Website</strong> refers to the website, accessible from <a href="https://www.doriaarnaud.online" rel="external nofollow noopener" target="_blank" class="text-subtitle-1">https://www.doriaarnaud.online</a></p>
          </li>
          <li>
            <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
          </li>
          <li>
            <p><strong>We, Our, Us</strong> means the sevice provider, the person that appear, owner and reachable via the ONLY contact address on this site.</p>
          </li>
        </ul>
        <h2 class="mt-2">Languages</h2>
        <p>We use English(US) and French(FR) for all information exchanges, contacts and discussions.</p>
        <h2 class="mt-5 mb-5">Collecting and Using Your Personal Data</h2>
        <h3 class="mt-2">Types of Data Collected</h3>
        <h4>Personal Data</h4>
        <p>
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information include and limited to these following:
        </p>
        <h4>Usage Data</h4>
        <p>Usage Data is collected automatically when using the Service.</p>
        <h4>Tracking Technologies and Cookies</h4>
        <p>This website has no functionalities to get location or track Your device including Cellphone, Tablet or Computer and never read/write cookies on Your devices.</p>
        <h3>Use of Your Personal Data</h3>
        <p>We may use Personal Data for the following purposes:</p>
        <ul class="ms-5">
          <li>
            <p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>
          </li>
          <li>
            <p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
          </li>
          <li>
            <p><strong>To contact You:</strong> To contact You by email, or other equivalent forms of electronic communication, related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
          </li>
          <li>
            <p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.Note that request processing is from older to newer.</p>
          </li>
          <li>
            <p><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
          </li>
        </ul>
        <p>We never share Your personal information, especially the e-mail address or a secondary contact to a third-party.</p>
        <h3>Retention of Your Personal Data</h3>
        <p>We will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
        <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
        <h3>Delete Your Personal Data</h3>
        <p>You have the right to delete or request an e-mail deletion via the contact link below, the Personal Data that We have collected about You. After that, this means we don't have any relations or contact anymore and we will not responsible of any other person or a third-party trying to remake a link with You.</p>
        <h3>Disclosure of Your Personal Data</h3>
        <h4>Other legal requirements</h4>
        <p>We may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul class="ms-5">
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of Us</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
        </ul>
        <h3>Security of Your Personal Data</h3>
        <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data. We do our best to keep Your security.The person, owner and service provider appearing and reachable with the only contact on this website can access all of these informations.</p>
        <h2 class="mt-2">Children's Privacy</h2>
        <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13, We remove that information.
        Anyone having a device able to connect to the internet can visit this site.There is no explicit content but in case of using Our services and entertaining a contact with Us, You should have 18 years old or above. A physical person, entity or company representative that could take a decision in any situations.</p>
        <h2 class="mt-2">Links to Other Websites</h2>
        <p>Our Service contain links to other websites that are operated by Us.These internal links are not a third-party but only Our subdomains, You will be directed to that sample project's site.</p>
        <h2 class="mt-2">Changes to this Privacy Policy</h2>
        <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
        <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
        <h2 class="mt-2">Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul class="ms-5">
        <li class="mb-5">
          By email:
            <a href="mailto:online.doriaarnaud@gmail.com">
              online.doriaarnaud@gmail.com
            </a>
        </li>
        </ul>
      </div>
    </v-card>
  </v-dialog>
</template>

<script>
</script>

<style>
  div.privacycontainer
  {
    background-color: #101019;
    color:#ffffff;
  }
  div.privacycontainer a
  {
    color:#ffffff;
  }
  p#cp
  {
    text-align: center;
    color:#ffffff;
  }
  span#privacybtn
  {
    background-color:none;
    text-decoration: underline;
  }
  span#privacybtn:hover
  {
    cursor:pointer;
  }
</style>
